; =====================================================================
; Gateway Node — ESP32 + Ethernet W5500 (RJ45) + MQTT publisher
; Root node dari ESP-MESH, menjembatani data sub-edge ke local server
; =====================================================================
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    painlessMesh/painlessMesh @ ^1.5.0
    bblanchon/ArduinoJson @ ^6.21.5
    knolleary/PubSubClient @ ^2.8
    ; Driver Ethernet W5500 (SPI) — gunakan salah satu sesuai modul:
    arduino-libraries/Ethernet @ ^2.0.2

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1

board_build.partitions = default.csv
