[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    painlessMesh/painlessMesh @ ^1.5.0
    bblanchon/ArduinoJson @ ^6.21.5
    adafruit/Adafruit MLX90614 Library @ ^2.1.5
build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
board_build.partitions = default.csv
